server:
  port: 80
spring:
  application:
    name: yunsang
  datasource:
    url: jdbc:h2:mem:hdjunction
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      schema-locations: classpath:/sql/create_schema.sql
      data-locations: classpath:/sql/insert_data.sql