server:
  port: 80
spring:
  application:
    name: yunsang
  datasource:
    master:
      url: jdbc:h2:mem:hdjunction
      driver-class-name: org.h2.Driver
      username: sa
      password:
    slave:
      url: jdbc:h2:mem:hdjunction
      driver-class-name: org.h2.Driver
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2-console