server:
  port: 80
spring:
  application:
    name: yunsang
  datasource:
    url: jdbc:h2:mem:hdjunction
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    hibernate:
      ddl-auto: none # 아래 sql파일(init path)로 초기화진행하므로 설정하지 않음
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      schema-locations: classpath:/sql/create_schema.sql
      data-locations: classpath:/sql/insert_data.sql